const initial = [
[1,'Viola','Little Girl','Nervous Records','NE 20478','US','2001','Club Mix; Put Cha Dub; A Small Dub 6:20; Warm Demo Mix 8:31',false],
[2,'The Advent','Panther EP','Kombination Research','KR005 / KRESEARCH 005','UK','1998','Panther 4:08; Black Patch 4:44; True Combo',false],
[3,'Rising High Collective','Fever Called Love','Rising High Records','RSN 57','UK','1993','Hardfloor Mix 7:18; Original Mix 8:29',false],
[4,'Unknown','','','','','','Abstract pink/orange/white label',true],
[5,'Unknown','','','','','','Black/magenta geometric label',true],
[6,'Unknown','Nu Drum Drops Vol. 2','Rey-D Records','','','','White label, barcode 7 67213 19741 4',true],
[7,'Prinni','Peacemaker','Loöq Records','LoQ 008','UK','','',true],
[8,'Ruff Beats Presents DJ Demigod','D-Day E.P.','Ruff Beats Records','RB017','US','1997','OG Live; Violence Within; Dopest First',false],
[9,'Pulse','Shut Up Already!','Bassment Records','BM-0051','US','1987','Fierce Mix 4:10; Samplepella Mix 3:05; Pulsating Mix; Piano Dub',false],
[10,'Various Artists','Lapse Records','Lapse Records','LAPSE001','Germany','2021','Buran 6:31; Ekranoplan 6:36; Every Week 8:02; Happy Trance 7:41',false],
[11,'Genetic Bass','Frustrate E.P.','Djax-Up-Beats','DJAX-UP-131','Netherlands','1991','S-1 4:15; S-2 4:28; S-3 3:44; S-4 3:45',false],
[12,'N-Joi','Malfunction','RCA','RDCC62006-1 / RCA 62006-1','US','1991','Malfunction 4:20; Manic 2:37; Techno Gangsters 3:33',false],
[13,'Unknown','','Nervous Records','','US','','Yellow Nervous label, NOT Storm',true],
[14,'Storm','Storm','Positiva','12TIVDJX 94','UK','1998','Man With No Name Remix; Rollercoaster\'s Pumped Up Mix',false],
[15,'DJ Godfather','Who\'s That DJ?','Databass Records','DB061','US','2005','',false],
[16,'Fit Siegel','','','','','','Dark brown/marbled label',true],
[17,'Jeremiah','Only Dubbin\' On My 808','Grow!','GROW! 26','Austria','2000','Only Dubbin\' On My 808; Un Dia Soleado',false],
[18,'Danger Man','Circulation','Circulation','CM 001','','','Artist/title orientation needs verification',true],
[19,'Allan M','Self Confidence','','','','','Self Confidence; Soho Step; 2Vilas Remix; Malin Genie Remix',true],
[20,'007','Atmosphere','Odyssey Recordings','OD-02','US','1995','Atmosphere (Electro Funk Mix); Electro Beats',true],
[21,'Ibex','The Second Coming / Pandora\'s Box','Ibex Music','','US','2008','Produced by Tony Ollivierra',false],
[22,'Sansibar','Targeted Individuals','Darknet','DN-01 / DN-001','Germany','2020','Liquid Programming; Technology; My Mind; Meri; 4Digitghost; Kaista; Body Rock; Noche',false],
[23,'Hex Hector / Aki Nawaz','Theme From Love / Sunya','Whirling Records','','','','Exact structure unresolved',true],
[24,'Various Artists / Andrew Weatherall','Nine O\'Clock Drop','Nuphonic','NUX151','UK','2000','13-track 2LP compilation',false],
[25,'Various Artists','Brooklyn Swoop','','','US','','Courtesy of Fumero visible, label unresolved',true],
[26,'Unknown','Nothing Changes / Uro / Hauz','2-Inch Single','','','','Exact artist/label/year unresolved',true],
[27,'Disco Invaders','Dropping Drummer','','','','','',true],
[28,'Unknown','Aurora Borealis','','','','','Exact pressing unresolved',true],
[29,'Strait 2 Dat','You\'re In Da House / I Did This 4 Da Shelter','Nervous Records','','US','','',true],
[30,'Wayne Folk','Man Of Many Faces','','','','','',true],
[31,'Smith n Hack','Tribute','Smith n Hack','SMITH001','Germany','2003','No Gimmicks, No Flash; Soul Food; Footstomping Smoker',false],
[32,'Wyatt Earp & Jonas Tempel feat. Stacy Briscoe','Frequency','Hochokai','HR007','US','2003','Original Mix; Ty Tek & Little Mike Remix',false],
[33,'James Hardway','Cool Jazz Mother Fucker EP','Substance','','','','',true],
[34,'DJ Andi K','Spanish Ice / Stop The Music','Version 3.0','#009','','','',true],
[35,'Soulsonic Force','Trans-Europe Express / Planet Rock','Master Cuts','MC-6028','US','','Unofficial 12-inch',true],
[36,'Tito Puente Jr.','Azúcar','La Casa','LC0001','US','','Radio Edit 3:48; Extended House 8:47; Tropi Club Intro 6:18',true],
[37,'Mihigh + Paul K','Unified Field','Melodrom','MELODROM_02','Romania','','Light of Unity 12:59; Inside 12:23',true],
[38,'Unknown','','Airwave','','','','Airwave logo/boombox artwork only',true]
].map(r=>({number:r[0],artist:r[1],release:r[2],label:r[3],catno:r[4],country:r[5],year:r[6],tracks:r[7],unresolved:r[8],discogsId:'',media:'VG+',sleeve:'VG+',numForSale:'',lowestPrice:'',currency:'',askingPrice:'',discogsUrl:'',marketplaceStatus:'Pending'}));

const STORAGE='carlos-vinyl-inventory-v1';
let rows = load();
let filter='all';
let query='';
let active=null;
const app=document.querySelector('#app');

function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE));if(Array.isArray(x)&&x.length)return x}catch{}return structuredClone(initial)}
function save(){localStorage.setItem(STORAGE,JSON.stringify(rows));render();}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(r){return r.lowestPrice ? `${r.currency||'$'} ${Number(r.lowestPrice).toFixed(2)}` : ''}
function counts(){return{total:rows.length,resolved:rows.filter(r=>!r.unresolved).length,unresolved:rows.filter(r=>r.unresolved).length,priced:rows.filter(r=>r.lowestPrice).length}}
function filtered(){return rows.filter(r=>{const f=filter==='all'||(filter==='unresolved'&&r.unresolved)||(filter==='priced'&&r.lowestPrice)||(filter==='linked'&&r.discogsId);const hay=[r.number,r.artist,r.release,r.label,r.catno,r.country,r.year].join(' ').toLowerCase();return f&&hay.includes(query.toLowerCase())})}

function render(){const c=counts();app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div><div class="eyebrow">Personal Vinyl Inventory</div><div class="title">Carlos Vinyl Catalog</div><div class="subtitle">Discogs-assisted research, grading, pricing and export</div></div><div class="status"><span id="tokenDot" class="dot"></span><span id="tokenText">Checking Discogs connection…</span></div></div><div class="metrics"><div class="metric"><b>${c.total}</b><span>Total records</span></div><div class="metric"><b>${c.resolved}</b><span>Resolved</span></div><div class="metric"><b>${c.unresolved}</b><span>Needs verification</span></div><div class="metric"><b>${c.priced}</b><span>Marketplace priced</span></div></div></header>
<div class="toolbar"><input id="q" placeholder="Search artist, release, label, catalog number…" value="${esc(query)}"><select id="filter"><option value="all">All records</option><option value="unresolved">Needs verification</option><option value="linked">Discogs linked</option><option value="priced">Marketplace priced</option></select><button class="btn" id="xls">Export Excel</button><button class="btn" id="json">Backup JSON</button><button class="btn" id="print">Print / PDF</button><button class="btn" id="reset">Reset catalog</button></div>
<main class="content"><div class="mobile-list">${filtered().map(cardHtml).join('')}${filtered().length?'':'<div class="empty">No records match this filter.</div>'}</div><div class="table-card desktop-table"><div class="table-wrap"><table><thead><tr><th>#</th><th>Artist</th><th>Release</th><th>Label</th><th>Cat #</th><th>Country</th><th>Year</th><th>Media</th><th>Sleeve</th><th>Discogs ID</th><th>For Sale</th><th>Lowest</th><th>Ask</th><th>Status</th><th class="actions">Actions</th></tr></thead><tbody>${filtered().map(rowHtml).join('')}</tbody></table>${filtered().length?'':'<div class="empty">No records match this filter.</div>'}</div></div><div class="footer-note">Marketplace fields are populated only when Discogs returns them. Missing or restricted values stay blank instead of being estimated.</div></main><div id="drawer" class="drawer"><div class="panel" id="panel"></div></div></div>`;
const f=document.querySelector('#filter');f.value=filter;f.onchange=e=>{filter=e.target.value;render()};document.querySelector('#q').oninput=e=>{query=e.target.value;render()};document.querySelector('#xls').onclick=exportXls;document.querySelector('#json').onclick=exportJson;document.querySelector('#print').onclick=()=>window.print();document.querySelector('#reset').onclick=()=>{if(confirm('Reset all local edits and restore the original 38-record catalog?')){rows=structuredClone(initial);localStorage.removeItem(STORAGE);render()}};
document.querySelectorAll('[data-edit]').forEach(el=>el.onchange=e=>edit(Number(el.dataset.n),el.dataset.edit,e.target.value));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDrawer(Number(b.dataset.open)));document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>refreshMarket(Number(b.dataset.market),b));checkStatus();}

function cardHtml(r){const status=r.unresolved?'<span class="tag warn">VERIFY</span>':r.discogsId?'<span class="tag ok">LINKED</span>':'<span class="tag muted">KNOWN</span>';return `<article class="record-card ${r.unresolved?'unresolved':''}"><div class="record-card-head"><div><div class="record-number">#${r.number}</div><div class="record-title">${esc(r.artist||'Unknown')}</div><div class="record-release">${esc(r.release||'Untitled')}</div></div>${status}</div><div class="record-meta"><span>${esc(r.label||'Label unknown')}</span><span>${esc(r.catno||'Cat # unknown')}</span><span>${esc([r.country,r.year].filter(Boolean).join(' · ')||'Year unknown')}</span></div><div class="record-grid"><label>Media<select class="cell-select" data-edit="media" data-n="${r.number}">${['M','NM','VG+','VG','G+','G','F','P'].map(o=>`<option ${r.media===o?'selected':''}>${o}</option>`).join('')}</select></label><label>Sleeve<select class="cell-select" data-edit="sleeve" data-n="${r.number}">${['M','NM','VG+','VG','G+','G','F','P'].map(o=>`<option ${r.sleeve===o?'selected':''}>${o}</option>`).join('')}</select></label><label>For sale<div class="mobile-value">${esc(r.numForSale||'—')}</div></label><label>Lowest<div class="mobile-value">${esc(money(r)||'—')}</div></label><label>Asking<input class="cell-input money" data-edit="askingPrice" data-n="${r.number}" value="${esc(r.askingPrice)}" placeholder="$"></label><label>Discogs ID<input class="cell-input" data-edit="discogsId" data-n="${r.number}" value="${esc(r.discogsId)}" inputmode="numeric"></label></div><div class="record-actions"><button class="btn primary" data-open="${r.number}">Research</button><button class="btn" data-market="${r.number}" ${r.discogsId?'':'disabled'}>Refresh price</button></div></article>`}

function rowHtml(r){const status=r.unresolved?'<span class="tag warn">VERIFY</span>':r.discogsId?'<span class="tag ok">LINKED</span>':'<span class="tag muted">KNOWN</span>';return `<tr class="${r.unresolved?'unresolved':''}"><td class="num">${r.number}</td>${inputTd(r,'artist',150)}${inputTd(r,'release',170)}${inputTd(r,'label',120)}${inputTd(r,'catno',105)}${inputTd(r,'country',80)}${inputTd(r,'year',58)}${selectTd(r,'media')}${selectTd(r,'sleeve')}<td><input class="cell-input" data-edit="discogsId" data-n="${r.number}" value="${esc(r.discogsId)}" style="width:74px"></td><td class="money">${esc(r.numForSale)}</td><td class="money nowrap">${esc(money(r))}</td><td><input class="cell-input money" data-edit="askingPrice" data-n="${r.number}" value="${esc(r.askingPrice)}" placeholder="$"></td><td>${status}</td><td class="actions"><button class="mini blue" data-open="${r.number}">Research</button> <button class="mini" data-market="${r.number}" ${r.discogsId?'':'disabled'}>Price</button></td></tr>`}
function inputTd(r,k,w){return `<td><input class="cell-input" style="min-width:${w}px" data-edit="${k}" data-n="${r.number}" value="${esc(r[k])}"></td>`}
function selectTd(r,k){const opts=['M','NM','VG+','VG','G+','G','F','P'];return `<td><select class="cell-select" data-edit="${k}" data-n="${r.number}">${opts.map(o=>`<option ${r[k]===o?'selected':''}>${o}</option>`).join('')}</select></td>`}
function edit(n,k,v){const r=rows.find(x=>x.number===n);if(!r)return;r[k]=v;if(['artist','release','label','catno','country','year'].includes(k)&&v.trim()) r.unresolved = !r.artist || !r.release || !r.label || !r.catno || !r.year;save()}

async function checkStatus(){try{const r=await fetch('/api/status');const j=await r.json();const dot=document.querySelector('#tokenDot');const text=document.querySelector('#tokenText');if(!dot)return;dot.className='dot '+(j.tokenConfigured?'ok':'');text.textContent=j.tokenConfigured?'Discogs token connected':'Discogs token not configured'}catch{}}
function openDrawer(n){active=rows.find(r=>r.number===n);const d=document.querySelector('#drawer'),p=document.querySelector('#panel');d.classList.add('open');const search=[active.artist,active.release,active.catno].filter(Boolean).join(' ');p.innerHTML=`<div class="panel-head"><div><div class="eyebrow" style="color:#667085">Record ${active.number}</div><h2>${esc(active.artist||'Unknown')} · ${esc(active.release||'Untitled')}</h2></div><button class="close" id="close">×</button></div><div class="section"><h3>Discogs Search</h3><div class="search-row"><input id="dsq" value="${esc(search)}"><button class="btn primary" id="dsgo">Search</button></div><div id="searchMsg" class="note" style="margin-top:8px">Search by artist, release title or catalog number, then select the exact pressing.</div><div id="results" class="results"></div></div><div class="section"><h3>Current record</h3><div class="note">Discogs ID: <b>${esc(active.discogsId||'Not linked')}</b><br>Tracks/notes: ${esc(active.tracks||'None entered')}<br>Media: ${esc(active.media)} · Sleeve: ${esc(active.sleeve)}</div></div><div id="detail"></div>`;document.querySelector('#close').onclick=closeDrawer;d.onclick=e=>{if(e.target===d)closeDrawer()};document.querySelector('#dsgo').onclick=searchDiscogs;if(active.discogsId)loadDetail(active.discogsId)}
function closeDrawer(){document.querySelector('#drawer')?.classList.remove('open');active=null}
async function searchDiscogs(){const q=document.querySelector('#dsq').value.trim(),msg=document.querySelector('#searchMsg'),out=document.querySelector('#results');if(!q)return;msg.textContent='Searching Discogs…';out.innerHTML='';try{const r=await fetch('/api/search?q='+encodeURIComponent(q));const j=await r.json();if(!r.ok)throw new Error(j.error||'Search failed');msg.textContent=`${j.results.length} results`;out.innerHTML=j.results.map(x=>`<div class="result">${x.thumb?`<img class="thumb" src="${esc(x.thumb)}">`:'<div class="thumb"></div>'}<div><div class="result-title">${esc(x.title)}</div><div class="result-meta">${esc([x.label,x.catno,x.country,x.year,x.format].filter(Boolean).join(' · '))}</div></div><button class="mini blue" data-pick="${x.id}">Use</button></div>`).join('');out.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>pickRelease(Number(b.dataset.pick)))}catch(e){msg.innerHTML=`<span class="error">${esc(e.message)}</span>`}}
async function pickRelease(id){if(!active)return;active.discogsId=String(id);await loadDetail(id,true);save();openDrawer(active.number)}
async function loadDetail(id,apply=false){const box=document.querySelector('#detail');if(!box)return;box.innerHTML='<div class="section"><div class="note">Loading release details…</div></div>';try{const r=await fetch('/api/release/'+id),j=await r.json();if(!r.ok)throw new Error(j.error||'Release lookup failed');if(apply&&active){active.artist=j.artists||active.artist;active.release=j.title||active.release;active.year=String(j.year||active.year);active.country=j.country||active.country;if(j.labels?.[0]){active.label=j.labels[0].name||active.label;active.catno=j.labels[0].catno||active.catno}active.discogsUrl=j.uri?`https://www.discogs.com${j.uri}`:'';active.tracks=(j.tracklist||[]).map(t=>`${t.position} ${t.title}${t.duration?' '+t.duration:''}`.trim()).join('; ');active.unresolved=false}
box.innerHTML=`<div class="section"><h3>Discogs release</h3><div class="note"><b>${esc(j.artists)}</b> · ${esc(j.title)}<br>${esc([j.labels?.[0]?.name,j.labels?.[0]?.catno,j.country,j.year].filter(Boolean).join(' · '))}${active?.discogsUrl?`<br><a class="discogs-link" target="_blank" href="${esc(active.discogsUrl)}">Open on Discogs</a>`:''}</div></div><div class="section"><h3>Track list</h3><table class="tracks"><tbody>${(j.tracklist||[]).map(t=>`<tr><td style="width:55px">${esc(t.position)}</td><td>${esc(t.title)}</td><td style="width:70px">${esc(t.duration)}</td></tr>`).join('')||'<tr><td>No track list returned.</td></tr>'}</tbody></table></div><div class="section"><h3>Marketplace</h3><button class="btn primary" id="detailPrice">Refresh marketplace stats</button><div id="marketMsg" class="note" style="margin-top:8px"></div></div>`;document.querySelector('#detailPrice').onclick=()=>refreshMarket(active.number,null,true)}catch(e){box.innerHTML=`<div class="section error">${esc(e.message)}</div>`}}
async function refreshMarket(n,btn,inside=false){const r=rows.find(x=>x.number===n);if(!r?.discogsId)return;if(btn)btn.disabled=true;const msg=inside?document.querySelector('#marketMsg'):null;if(msg)msg.textContent='Checking Discogs marketplace…';try{const res=await fetch('/api/marketplace/'+r.discogsId),j=await res.json();if(!res.ok)throw new Error(j.error||'Marketplace lookup failed');if(j.available){r.numForSale=j.numForSale??'';r.lowestPrice=j.lowestPrice?.value??'';r.currency=j.lowestPrice?.currency??'';r.marketplaceStatus='Available';if(msg)msg.innerHTML=`<span class="success">${esc(String(r.numForSale||0))} for sale · lowest ${esc(money(r)||'not returned')}</span>`}else{r.marketplaceStatus='Unavailable';if(msg)msg.innerHTML=`<span class="error">Marketplace stats unavailable: ${esc(j.reason||'restricted')}</span>`}localStorage.setItem(STORAGE,JSON.stringify(rows));if(!inside)render()}catch(e){r.marketplaceStatus='Error';if(msg)msg.innerHTML=`<span class="error">${esc(e.message)}</span>`;if(!inside)render()}finally{if(btn)btn.disabled=false}}

function exportJson(){download('Carlos_Vinyl_Inventory.json',JSON.stringify(rows,null,2),'application/json')}
function exportXls(){const cols=['#','Artist','Release','Label','Catalog Number','Country','Year','Media Condition','Sleeve Condition','Discogs ID','Copies For Sale','Lowest Price','Currency','Asking Price','Status','Tracks / Notes'];const body=rows.map(r=>[r.number,r.artist,r.release,r.label,r.catno,r.country,r.year,r.media,r.sleeve,r.discogsId,r.numForSale,r.lowestPrice,r.currency,r.askingPrice,r.unresolved?'Needs verification':r.marketplaceStatus,r.tracks]);const table=`<table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${body.map((a,i)=>`<tr style="${rows[i].unresolved?'background:#fff0c2':''}">${a.map(v=>`<td>${esc(v??'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;const html=`<html><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Arial;font-size:10pt}th{background:#0d1b2a;color:white;font-weight:bold;padding:6px;border:1px solid #9aa4b2}td{padding:5px;border:1px solid #c7cdd5}</style></head><body>${table}</body></html>`;download('Carlos_Vinyl_Inventory.xls',html,'application/vnd.ms-excel')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
render();
